### ISSUE TITLE
Hookd rapporterer ikke deployment failed til github

### ISSUE THREAD

**Issue by mortenlj** [nais/deploy#102]
https://nav-it.slack.com/archives/C5KUST8N6/p1677154279434859

Jeg klarer ikke helt se hva som skjer her. Såvidt jeg kan skjønne så har deployd rapportert status tilbake til hookd, om at dette gikk galt. Videre så logget hookd deployment failed etter ett sekund eller noe, men hvorfor den ikke rapporterte det videre til github klarte jeg ikke finne ut av. Koden er litt for innviklet til at jeg helt klarer å grave meg tilbake til hvordan det skal fungere ...

**Comment by mortenlj** [comment]
Prøvde å se litt mer på det nå, og forstår fortsatt ikke helt hvorfor det aldri kom frem ... men jeg fant en linje som jeg syns er suspekt uten at jeg kan si hvorfor den skulle føre til dette problemet.
https://github.com/nais/deploy/blob/master/pkg/grpc/dispatchserver/broker.go#L68

`s.statuses` blir bare opprettet i `New`, med capacity 4096, og så dytter vi statuser dit. Klarer ikke finne noe sted hvor de tas ut igjen ...

**Comment by mortenlj** [comment]
Vi bør prøve å reprodusere med en spec som ligner på den i den opprinnelige slack-tråden, og se om vi får samme feil igjen.

**Comment by sechmann** [comment]
Har basert på feilmeldingen prøvd å gjenskape feilen (repoet er slettet ser det ut som, så finner ikke naisfila som ble forsøkt deployet den gangen)

forsøkt med:
```
apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: aura
  name: test-invalid-env-vegar
  namespace: aura
spec:
  command:
  - perl
  - -le
  - sleep(40);print 'job complete'
  image: navikt/perl
  skipCaBundle: true
  env:
  - name: "INVALID"
    value: 1
```

```
go run ./cmd/deploy/ --resource ./job.yaml --cluster dev-gcp --team aura
```

Jeg får bare valideringsfeil (som forventet) når jeg forsøker. Tror vi er avhengig av at dette skjer igjen for å feilsøke videre. Lukker inntil det evt. oppstår igjen.
