### ISSUE TITLE
Flytte CDN-deploy action til nais/deploy

### ISSUE THREAD

**Issue by kimtore** [nais/deploy#232]
Original tråd: https://nav-it.slack.com/archives/C050DP53VPH/p1728544871543309

- [x] Flytte workflows til Nais action
- [x] Slette action fra Navikt
- [x] Dokumentere CDN action_s_ i [docs.nais.io](http://docs.nais.io/)
- [x] Oppdatere actions sin interne dokumentasjon
- [x] Påse at actions ikke bruker Navikt-actions internt (har fikset en feil)
- [x] Legge til støtte for egne domener
- [ ] Byggepipeline
- [ ] Drodle om mulig støtte for NaaS

**Comment by Kyrremann** [comment]
Starter med å oppdatere dokumentasjonen.

**Comment by Kyrremann** [comment]
Sykt mange som bruker v1, og ikke nye nais/login...

**Comment by Kyrremann** [comment]
Da funker egne domener også:
```yaml
      - name: Deploy doc to leesah.io
        id: deploy
        uses: nais/deploy/actions/spa-deploy/v2@master
        with:
          app: leesah-produktside
          team: leesah-quiz
          source: doks/dist
          ingress: https://leesah.io
          ingressClass: nais-ingress-external
          environment: prod-gcp
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
```
