### ISSUE TITLE
Improve support for Mono Git repo setup (make environment variables from deploy.yml available in nais ?)

### ISSUE THREAD

**Issue by alpet** [nais/deploy#69]
Hi, I have been trying to define a Mono Git Repos setup where I have multiple small microservices available in the same repo. In order to do that I defined 2 nais files and 2 Docker files one for each microservice. On top I have one deploy.yml file supplied with 2 deploy jobs one for each service.

https://github.com/navikt/pensjon-brev-bestilling/blob/features/PL-2357-add-prepare-brevdata/.github/workflows/deploy.yaml

Each nais.yml  exposes a single interpolated variable {{image}}. This mean that I can not refer to the top level "env" variables `IMAGE_BREV_BESTILLING `and  `IMAGE_PREPARE_BREVDATA_GRUNNLAG `direclt.

The work around is to assign each of this environment variables to the "IMAGE" variable from within each job:
```
env:
        IMAGE: ${{env.IMAGE_PREPARE_BREVDATA_GRUNNLAG}}

```
--------------------------------------------------------------------------------------------------------------------------------------------
One way to improve this would be to make available the env variables to the nais.yml. Or if this is not desire to make available some pattern for variables f.ex. all variables starting with "IMAGE_%"

In the nais documentation when someone is reading it it is not imediatly clear that {{image}} is not environment variable and the example is very well placed for a Poly repositry , but it is not immediatly clear how would a Mono repo look like(especaly if the reader is convinced that image is env variable as I wasin the begining).

Maybe a addition to the documentation listing all "interpolated" variables would be nice.

**Comment by Kyrremann** [comment]
Kom på noe, som kanskje @ambientsound kan bekrefte. Jeg lurer på om du kan sette miljøvariabler direkte i action-en, som da nais/deploy plukker opp, og spytter inn i yaml-en din. Så på samme måte som du spesifiserer cluster, så kan du også spesifisere en miljøvariabel for image.

**Comment by ambientsound** [comment]
Hi @alpet,

The current implementation just sets a variable in the variables file (if it is specified). Otherwise, it creates a new variable file and with `.image`.

https://github.com/nais/deploy/blob/master/actions/deploy/entrypoint.sh

If I understand correctly you would like to avoid setting `IMAGE: ${{env.IMAGE_BREV_BESTILLING}}` and similar for all the different deploy jobs? I'm not sure how useful this would be, but you can try the solution below.

If you'd like to put all the `IMAGE_` environment variables into your variable file, you can use a shell script as follows:

```
# these come from Github Actions
% export IMAGE_FOO=my/image:version IMAGE_BAR=other/image:otherversion

% env | grep 'IMAGE_' | awk -F'=' '{print $1 ": " $2}' > nais/vars.yaml
% cat nais/vars.yml
IMAGE_FOO: my/image:version
IMAGE_BAR: other/image:otherversion
```

Then specify that you want to use a custom variable file in the action:

```
- uses: nais/deploy/actions/deploy@v1  
  env:
    APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
    CLUSTER: dev-fss
    RESOURCE: nais/nais-brev-bestilling.yml
    VARS: nais/vars.yml
```

Now you can use it in your `nais.yml` file:

```
spec:
  image: {{ IMAGE_FOO }}
```

**Comment by ambientsound** [comment]
> Kom på noe, som kanskje @ambientsound kan bekrefte. Jeg lurer på om du kan sette miljøvariabler direkte i action-en, som da nais/deploy plukker opp, og spytter inn i yaml-en din. Så på samme måte som du spesifiserer cluster, så kan du også spesifisere en miljøvariabel for image.

This feature exists, but in this case I don't think this is useful, as it would require specifying the image again?

```
- uses: nais/deploy/actions/deploy@v1  
  env:
    APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
    CLUSTER: dev-fss
    RESOURCE: nais/nais-brev-bestilling.yml
    VAR: IMAGE_FOO=${{ env.IMAGE_PREPARE_BREVDATA_GRUNNLAG }},IMAGE_BAR=${{ env.IMAGE_PREPARE_BREVDATA_GRUNNLAG }}
```
