### ISSUE TITLE
Feature request: støtte flere dokumenter i nais.yaml

### ISSUE THREAD

**Issue by peterbb** [nais/deploy#75]
Ble litt overrasket over at det ikke fungerte å putte to resource-er i samme dokument og deploye de med `nais/deploy/actions/deploy@v1`. Siden det funker når man bruker `kubectl apply -f nais.yaml`, så tenkte jeg naivt at det kom til å funke med github-actionen deres.

Use-case er når man har tett koplede pods som skal deployes sammen. I mitt tilfelle `bitnami/redis:5.0.10` og `oliver006/redis_exporter:1.15.1`. 

### Eksempel 
Gitt at `nais.yaml` inneholder:
```yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: testapp1
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: navikt/nais-testapp:65.0.0

---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: testapp2
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: navikt/nais-testapp:65.0.0
```
så ønsker jeg at 
```sh
kubectl apply -f nais.yaml
```
og github actionen
```yaml
jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: nais.yaml
```
er ekvivalente.

Slik det er nå, så vil `kubectl` opprette begge nais-`application`-ene, mens github actionen kun en av dem.

(Edit: ser at man kommer nærme ved å liste opp flere filer i `RESOURCE`-parameteret, men hadde vært fint om kubectl og actionen støttet det samme.)
