### ISSUE TITLE
Feature request: Få med change-cause i deployment history

### ISSUE THREAD

**Issue by erik-a-e** [nais/deploy#76]
Er det mulig å gjøre noe med deploy via github actions, slik at følgende kommando:
`kubectl rollout history deployment <appnavn> -n <teamnamespace>`
kan gi tilbake noe mer beskrivende enn:
```
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
3         <none>
...
```
?
F.eks git commit og/eller tidspunkt hadde vært nyttig (edited)

**Comment by Sechmann** [comment]
forslag: la de som deployer hva de vil legge inn som cause i action
```
- uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: nais.yml
        VAR: image=${{ env.docker_image }}
        CAUSE=${{ github.event.head_commit.message }}
```
